### ISSUE TITLE
function live() not defined

### ISSUE THREAD

**Issue by grayhatdevelopers** [SaadBazaz/The-Code-of-Life#1]
I tried your life saving program, but it crashes with the error saying "function live() not defined".
Kindly resolve this issue.

**Comment by SaadBazaz** [comment]
Hi, @grayhatdevelopers. The purpose of this code is to give you the freedom to create your own "life" - I want to encourage developers and normal people to make fun, insightful and unique pull requests with their own definition of the life ( ) function. Life is strange and beautiful, let us embrace it and see the best in each other. 
Hope you participate!
